#!/usr/bin/env python3
"""Rebuild the vendored confusable-character table from Unicode UTS #39.

The upstream file is 700 kB of mappings covering every script pair. What this
tool needs is the reverse view, and only for characters that can appear in a
domain name: given an ASCII character, which single Unicode characters look
like it *and* survive UTS #46 processing as something different.

That last condition removes most of the file. Fullwidth "ａ", for instance, is
confusable with "a", but a browser folds it back to "a", so it is not a
distinct registration and not an attack. Roughly nine hundred such mappings are
dropped, along with duplicates that encode to the same punycode label.

    uv run python scripts/refresh_confusables.py

Output format, one substitution per line:

    <ascii target> TAB <code point, hex> TAB <script> TAB <character name>

Source: https://www.unicode.org/Public/security/latest/confusables.txt
Terms of use: https://www.unicode.org/terms_of_use.html
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

import httpx
import idna

SOURCE = "https://www.unicode.org/Public/security/latest/confusables.txt"
DESTINATION = (
    Path(__file__).resolve().parents[1] / "src" / "ctwatch" / "data" / "confusables_ascii.tsv"
)
DOMAIN_CHARACTERS = "abcdefghijklmnopqrstuvwxyz0123456789-"


# Words that start the descriptive part of a Unicode name; everything before
# the first one of them is the script, near enough for a human-readable label.
CATEGORY_WORDS = frozenset(
    {
        "CAPITAL",
        "SMALL",
        "LETTER",
        "DIGIT",
        "SYLLABICS",
        "LIGATURE",
        "MODIFIER",
        "SIGN",
        "VOWEL",
        "CHARACTER",
        "NUMBER",
        "SYMBOL",
        "MARK",
    }
)


def script_of(character: str) -> str:
    """The script a character belongs to, read off its Unicode name."""

    try:
        name = unicodedata.name(character)
    except ValueError:
        return "UNKNOWN"

    words: list[str] = []
    for word in name.upper().split():
        if word in CATEGORY_WORDS:
            break
        words.append(word)
    return " ".join(words) or "UNKNOWN"


def character_name(character: str) -> str:
    try:
        return unicodedata.name(character)
    except ValueError:
        return "UNNAMED"


def parse(text: str) -> dict[str, set[str]]:
    """Invert the upstream mapping: ASCII target -> confusable characters."""

    inverted: dict[str, set[str]] = {}
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        if len(fields) < 2:
            continue

        source_points = fields[0].split()
        target_points = fields[1].split()
        if len(source_points) != 1 or len(target_points) != 1:
            continue

        source = chr(int(source_points[0], 16))
        target = chr(int(target_points[0], 16)).lower()
        if target not in DOMAIN_CHARACTERS:
            continue
        inverted.setdefault(target, set()).add(source)
    return inverted


def keep_distinct(target: str, sources: set[str]) -> list[str]:
    """Drop substitutions that are not, in a domain name, actually different."""

    kept: list[str] = []
    seen_encodings: set[str] = set()
    # Domain labels are case-folded before encoding, so the lowercase form is
    # the one that actually appears in a registration.
    folded = sorted({source.lower() for source in sources})
    for source in folded:
        if len(source) != 1:
            continue
        probe = f"a{source}a"
        try:
            encoded = idna.encode(probe, uts46=True, std3_rules=False).decode("ascii")
        except idna.IDNAError:
            continue
        if not encoded.startswith("xn--") or encoded == f"a{target}a":
            continue
        if encoded in seen_encodings:
            # Several code points can normalise to the same label; one of them
            # is enough, and the lowest is the one attackers reach for.
            continue
        seen_encodings.add(encoded)
        kept.append(source)
    return kept


def main() -> int:
    response = httpx.get(SOURCE, timeout=90.0, follow_redirects=True)
    response.raise_for_status()
    text = response.content.decode("utf-8-sig")

    if "confusables.txt" not in text[:200]:
        print("refusing to parse a file that does not look like confusables.txt", file=sys.stderr)
        return 1

    inverted = parse(text)
    lines: list[str] = [
        "# Confusable characters, reduced to what matters for domain names.",
        "# Generated by scripts/refresh_confusables.py — do not edit by hand.",
        f"# Source: {SOURCE}",
        "# Terms of use: https://www.unicode.org/terms_of_use.html",
        "#",
        "# ascii\tcodepoint\tscript\tname",
    ]

    total = 0
    for target in sorted(inverted):
        for source in keep_distinct(target, inverted[target]):
            lines.append(
                f"{target}\t{ord(source):04X}\t{script_of(source)}\t{character_name(source)}"
            )
            total += 1

    DESTINATION.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"source       {SOURCE}")
    print(f"written      {DESTINATION}")
    print(f"targets      {len(inverted)}")
    print(f"substitutions {total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
